 
# name: Gemini Code Review Reusable
# on:
#   workflow_call:

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests pygithub

#       - name: Run Code Review
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GITHUB_REPOSITORY: ${{ github.repository }}
#           GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
#           GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
#         run: |
#           echo "Starting code review for PR #$GITHUB_EVENT_PULL_REQUEST_NUMBER in $GITHUB_REPOSITORY"
#           python .github/scripts/code_review.py
#           echo "Code review completed"

name: Gemini Code Review Reusable
on:
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout central-code-review-Bot repository
        uses: actions/checkout@v4
        with:
          repository: Code-Review-Org/central-code-review-Bot
          ref: main
          path: central-code-review-Bot

      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          path: calling-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygithub

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Starting code review for PR #$GITHUB_EVENT_PULL_REQUEST_NUMBER in $GITHUB_REPOSITORY"
          echo "GEMINI_API_KEY is set to: $GEMINI_API_KEY"
          python  central-code-review-Bot/.github/scripts/code_review.py
          echo "Code review completed"